# Generated by Django 4.2 on 2023-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
