# Generated by Django 4.2 on 2023-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
