# Generated by Django 4.2 on 2023-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_created=True, default=None),
        ),
        migrations.AddField(
            model_name="todo",
            name="last_updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
