# Generated by Django 4.2 on 2023-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_todo_created_at_todo_last_updated_todo_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
