# Generated by Django 4.2 on 2023-04-07 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="order",
            field=models.IntegerField(),
        ),
    ]
