# Generated by Django 4.2 on 2023-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0007_alter_todo_created_at_alter_todo_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="color",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
