# Generated by Django 4.2 on 2023-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0008_todo_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="color",
            field=models.IntegerField(default=10),
        ),
    ]
